version: '3.8'

services:
  db:
    image: mysql:5.7  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  
      MYSQL_DATABASE: students
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass  
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  api:
    build: .
    restart: always
    ports:
      - "8080:3000"
    env_file:
      - .env  
    depends_on:
      db:
        condition: service_healthy 

volumes:
  db_data:
