version: '3.1'
services:
  db:
    image: mysql:5.7  
    environment:
      MYSQL_ROOT_PASSWORD: ""  
      MYSQL_DATABASE: students
      MYSQL_USER: root
      MYSQL_PASSWORD: ""  
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  
  api:
    build: .
    ports:
      - "8080:3000"
    environment:
      DB_HOST: db  
      DB_USER: root  
      DB_PASSWORD: "" 
      DB_DATABASE: students
    depends_on:
      - db
volumes:
  db_data: